version: 1.0.{build}
image: Previous Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  project: DeviceManagerApi.sln
  verbosity: minimal
test:
  categories:
    except:
    - Integration